# This file is AUTO-GENERATED by generate_bookmarks_info.py
# Do not edit this file manually. Update the source file and regenerate.

# CALC_DATA = {
#     "adhd": {
#         "name": "بیش فعالی و عدم تمرکز",
#         "chart_name": "بیش‌فعالی",
#         "positive_labels": [
#             "attentionADHD",
#             "oddADHD",
#             "anxADHD",
#             "hyperADHD",
#             "cdADHD"
#         ],
#         "negative_labels": []
#     },
#     "anxiety": {
#         "name": "اضطراب",
#         "chart_name": "اضطراب",
#         "positive_labels": [
#             "anxGWB",
#             "bodyBAI",
#             "emoBAI",
#             "anxADHD",
#             "cogBAI",
#             "anSCL90"
#         ],
#         "negative_labels": []
#     },
#     "body_problem": {
#         "name": "مشکلات جسمی",
#         "chart_name": "مشکلات‌جسمی",
#         "positive_labels": [
#             "bodyBAI",
#             "behBDI",
#             "healthGWB"
#         ],
#         "negative_labels": [
#             "wellbeingPSSHI"
#         ]
#     },
#     "depression": {
#         "name": "افسردگی",
#         "chart_name": "افسردگی",
#         "positive_labels": [
#             "depGWB",
#             "emoBDI",
#             "behBDI",
#             "cogBDI",
#             "dpSCL90",
#             "depGWB"
#         ],
#         "negative_labels": []
#     },
#     "drug_addicion": {
#         "name": "اعتیاد به مواد مخدر",
#         "chart_name": "اعتیاد‌مواد",
#         "positive_labels": [
#             "internetIAT",
#             "gameACGQ",
#             "ocSCL90",
#             "ocd3"
#         ],
#         "negative_labels": [
#             "antisocialMESSY",
#             "impulsiveMESSY",
#             "narsMESSY"
#         ]
#     },
#     "family_problem": {
#         "name": "مشکلات خانوادگی",
#         "chart_name": "مشکلات‌خانوادگی",
#         "positive_labels": [
#             "contiSFI",
#             "leadingSFI",
#             "familyhealthSFI",
#             "emotionSFI",
#             "conflictSFI",
#             "connectionSFI"
#         ],
#         "negative_labels": [
#             "familysupportQRI",
#             "familydeptQRI",
#             "familyconflictQRI"
#         ]
#     },
#     "game_addiction": {
#         "name": "اعتیاد به بازی و اینترنت",
#         "chart_name": "اعتیاد‌گوشی",
#         "positive_labels": [
#             "internetIAT",
#             "gameACGQ",
#             "ocd3",
#             "ocd"
#         ],
#         "negative_labels": []
#     },
#     "interpersonal": {
#         "name": "مشکلات بین فردی",
#         "chart_name": "مشکلات‌بین‌فردی",
#         "positive_labels": [
#             "socialSE",
#             "passivephysicalAPRI",
#             "activesocialAPRI",
#             "passivesocialAPRI",
#             "activeverbalAPRI",
#             "passiveverbalAPRI",
#             "activephysicalAPRI"
#         ],
#         "negative_labels": [
#             "familysupportQRI",
#             "familydeptQRI",
#             "friendconflictQRI",
#             "socialskillsMESSY",
#             "impulsiveMESSY",
#             "relationMESSY",
#             "familyconflictQRI",
#             "friendsupportQRI",
#             "frienddeptQRI",
#             "antisocialMESSY",
#             "narsMESSY"
#         ]
#     },
#     "motivation": {
#         "name": "بی‌انگیزگی",
#         "chart_name": "بی‌انگیزگی",
#         "positive_labels": [
#             "cogBDI",
#             "generalSE",
#             "professionalSE",
#             "internalHEMS",
#             "extrnalHEMS",
#             "positiveGWB",
#             "internalSRQ",
#             "intrsicmotSRQ"
#         ],
#         "negative_labels": []
#     },
#     "ocd": {
#         "name": "وسواس",
#         "chart_name": "وسواس",
#         "positive_labels": [
#             "ocd",
#             "ocd1",
#             "ocd2",
#             "ocd3",
#             "ocd4",
#             "internetIAT",
#             "gameACGQ",
#             "ocSCL90",
#             "scontrolGWB"
#         ],
#         "negative_labels": []
#     },
#     "self_confident": {
#         "name": "اعتماد به نفس پایین",
#         "chart_name": "اعتمادبه‌نفس",
#         "positive_labels": [
#             "generalSE",
#             "professionalSE",
#             "socialSE",
#             "familySE",
#             "happyGWB",
#             "scontrolGWB"
#         ],
#         "negative_labels": [
#             "socialskillsMESSY"
#         ]
#     },
#     "sleep_problem": {
#         "name": "مشکلات خواب",
#         "chart_name": "مشکلات‌خواب",
#         "positive_labels": [
#             "sleepPSQ",
#             "bodyBAI",
#             "cogBAI"
#         ],
#         "negative_labels": []
#     },
#     "study_problem": {
#         "name": "نداشتن مهارت‌های مطالعاتی",
#         "chart_name": "مهارت‌های‌مطالعاتی",
#         "positive_labels": [],
#         "negative_labels": [
#             "timePSSHI",
#             "memoryPSSHI",
#             "readingPSSHI",
#             "examPSSHI",
#             "placePSSHI",
#             "motivationPSSHI",
#             "writtingPSSHI",
#             "wellbeingPSSHI"
#         ]
#     },
#     "truma": {
#         "name": "تروما دوران کودکی",
#         "chart_name": "تروما",
#         "positive_labels": [
#             "physneglectCTQ",
#             "physabuseCTQ",
#             "emoabuseCTQ",
#             "lieCTQ",
#             "emoneglectCTQ",
#             "sexualabuseCTQ"
#         ],
#         "negative_labels": []
#     },
#     "wage_future": {
#         "name": "نداشتن نصویر از آینده روشن",
#         "chart_name": "‌آینده‌مبهم",
#         "positive_labels": [
#             "internalHEMS",
#             "extrnalHEMS",
#             "intrsicmotSRQ",
#             "happyGWB",
#             "cogBDI",
#             "emoBDI"
#         ],
#         "negative_labels": [
#             "motivationPSSHI"
#         ]
#     },
#     "ideal": {
#         "name": "انتظارات زیاد دیگران",
#         "chart_name": "کمال‌گرایی",
#         "positive_labels": [
#             "internalHEMS",
#             "cogBDI",
#             "emoBDI"
#         ],
#         "negative_labels": [
#             "motivationPSSHI"
#         ]
#     },
# }

CALC_DATA = {
    "adhd": {
        "name": "بیش فعالی و عدم تمرکز",
        "chart_name": "بیش‌فعالی",
        "color": "#4DA3FF",  # energetic but controlled blue
        "positive_labels": [
            "attentionADHD",
            "oddADHD",
            "anxADHD",
            "hyperADHD",
            "cdADHD"
        ],
        "negative_labels": []
    },
    "anxiety": {
        "name": "اضطراب",
        "chart_name": "اضطراب",
        "color": "#5B5F97",  # indigo / alertness & worry
        "positive_labels": [
            "anxGWB",
            "bodyBAI",
            "emoBAI",
            "anxADHD",
            "cogBAI",
            "anSCL90"
        ],
        "negative_labels": []
    },
    "body_problem": {
        "name": "مشکلات جسمی",
        "chart_name": "مشکلات‌جسمی",
        "color": "#6CBF84",  # health & balance green
        "positive_labels": [
            "bodyBAI",
            "behBDI",
            "healthGWB"
        ],
        "negative_labels": [
            "wellbeingPSSHI"
        ]
    },
    "depression": {
        "name": "افسردگی",
        "chart_name": "افسردگی",
        "color": "#8A8D91",  # emotional flatness gray
        "positive_labels": [
            "depGWB",
            "emoBDI",
            "behBDI",
            "cogBDI",
            "dpSCL90",
            "depGWB"
        ],
        "negative_labels": []
    },
    "drug_addicion": {
        "name": "اعتیاد به مواد مخدر",
        "chart_name": "اعتیاد‌مواد",
        "color": "#C06C5C",  # muted red = risk without panic
        "positive_labels": [
            "internetIAT",
            "gameACGQ",
            "ocSCL90",
            "ocd3"
        ],
        "negative_labels": [
            "antisocialMESSY",
            "impulsiveMESSY",
            "narsMESSY"
        ]
    },
    "family_problem": {
        "name": "مشکلات خانوادگی",
        "chart_name": "مشکلات‌خانوادگی",
        "color": "#4FA3A5",  # relational teal
        "positive_labels": [
            "contiSFI",
            "leadingSFI",
            "familyhealthSFI",
            "emotionSFI",
            "conflictSFI",
            "connectionSFI"
        ],
        "negative_labels": [
            "familysupportQRI",
            "familydeptQRI",
            "familyconflictQRI"
        ]
    },
    "game_addiction": {
        "name": "اعتیاد به بازی و اینترنت",
        "chart_name": "اعتیاد‌گوشی",
        "color": "#9B6EDC",  # digital overstimulation purple
        "positive_labels": [
            "internetIAT",
            "gameACGQ",
            "ocd3",
            "ocd"
        ],
        "negative_labels": []
    },
    "interpersonal": {
        "name": "مشکلات بین فردی",
        "chart_name": "مشکلات‌بین‌فردی",
        "color": "#3FA7D6",  # social blue
        "positive_labels": [
            "socialSE",
            "passivephysicalAPRI",
            "activesocialAPRI",
            "passivesocialAPRI",
            "activeverbalAPRI",
            "passiveverbalAPRI",
            "activephysicalAPRI"
        ],
        "negative_labels": [
            "familysupportQRI",
            "familydeptQRI",
            "friendconflictQRI",
            "socialskillsMESSY",
            "impulsiveMESSY",
            "relationMESSY",
            "familyconflictQRI",
            "friendsupportQRI",
            "frienddeptQRI",
            "antisocialMESSY",
            "narsMESSY"
        ]
    },
    "motivation": {
        "name": "بی‌انگیزگی",
        "chart_name": "بی‌انگیزگی",
        "color": "#F2B705",  # faded yellow = low energy
        "positive_labels": [
            "cogBDI",
            "generalSE",
            "professionalSE",
            "internalHEMS",
            "extrnalHEMS",
            "positiveGWB",
            "internalSRQ",
            "intrsicmotSRQ"
        ],
        "negative_labels": []
    },
    "ocd": {
        "name": "وسواس",
        "chart_name": "وسواس",
        "color": "#7A5C9E",  # repetitive cognition purple
        "positive_labels": [
            "ocd",
            "ocd1",
            "ocd2",
            "ocd3",
            "ocd4",
            "internetIAT",
            "gameACGQ",
            "ocSCL90",
            "scontrolGWB"
        ],
        "negative_labels": []
    },
    "self_confident": {
        "name": "اعتماد به نفس پایین",
        "chart_name": "اعتمادبه‌نفس",
        "color": "#A0B2C8",  # soft desaturated blue
        "positive_labels": [
            "generalSE",
            "professionalSE",
            "socialSE",
            "familySE",
            "happyGWB",
            "scontrolGWB"
        ],
        "negative_labels": [
            "socialskillsMESSY"
        ]
    },
    "sleep_problem": {
        "name": "مشکلات خواب",
        "chart_name": "مشکلات‌خواب",
        "color": "#2F4858",  # night blue
        "positive_labels": [
            "sleepPSQ",
            "bodyBAI",
            "cogBAI"
        ],
        "negative_labels": []
    },
    "study_problem": {
        "name": "نداشتن مهارت‌های مطالعاتی",
        "chart_name": "مهارت‌های‌مطالعاتی",
        "color": "#7FB069",  # growth / learning green
        "positive_labels": [],
        "negative_labels": [
            "timePSSHI",
            "memoryPSSHI",
            "readingPSSHI",
            "examPSSHI",
            "placePSSHI",
            "motivationPSSHI",
            "writtingPSSHI",
            "wellbeingPSSHI"
        ]
    },
    "truma": {
        "name": "تروما دوران کودکی",
        "chart_name": "تروما",
        "color": "#6D597A",  # deep muted purple (sensitive)
        "positive_labels": [
            "physneglectCTQ",
            "physabuseCTQ",
            "emoabuseCTQ",
            "lieCTQ",
            "emoneglectCTQ",
            "sexualabuseCTQ"
        ],
        "negative_labels": []
    },
    "wage_future": {
        "name": "نداشتن نصویر از آینده روشن",
        "chart_name": "‌آینده‌مبهم",
        "color": "#E09F3E",  # uncertain future amber
        "positive_labels": [
            "internalHEMS",
            "extrnalHEMS",
            "intrsicmotSRQ",
            "happyGWB",
            "cogBDI",
            "emoBDI"
        ],
        "negative_labels": [
            "motivationPSSHI"
        ]
    },
    "ideal": {
        "name": "کمال‌گرایی",
        "chart_name": "کمال‌گرایی",
        "color": "#9C89B8",  # pressure & standards purple
        "positive_labels": [
            "socialSE",
            "activesocialAPRI",
            "passivesocialAPRI"
        ],
        "negative_labels": [
            "friendconflictQRI",
            "impulsiveMESSY",
            "antisocialMESSY",
            "narsMESSY"
            "narsMESSY"
        ]
    }
}

USER_TAGS_INFO = {
    "studentname": {
        "name": "نام و نام خانوادگی دانش آموز",
    },
    "instname": {
        "name": "نام موسسه",
    },
    "conname": {
        "name": "نام مشاور",
    },
}

COLOR_TAGS = {
    "adhd_so": {
        "tag_circle": "Adhd_so",
        "tag_triangle": "adhd_sh",
        "name": "بوکمارک تغییر رنگ اسمارت ابجکت بیش فعالی",
        "positive_labels": [],
        "negative_labels": []
    },
    "anxiety_so": {
        "tag_circle": "Anx_so",
        "tag_triangle": "anx_sh",
        "name": "بوکمارک تغییر رنگ اسمارت ابجکت اضطراب",
        "positive_labels": [],
        "negative_labels": []
    },
    "body_problem_so": {
        "tag_circle": "Body_so",
        "tag_triangle": "body_sh",
        "name": "بوکمارک تغییر رنگ اسمارت ابجکت مشکلات جسمی",
        "positive_labels": [],
        "negative_labels": []
    },
    "depression_so": {
        "tag_circle": "Dep_so",
        "tag_triangle": "dep_sh",
        "name": "بوکمارک تغییر رنگ اسمارت ابجکت افسردگی",
        "positive_labels": [],
        "negative_labels": []
    },
    "drug_addicion_so": {
        "tag_circle": "Addiction_so",
        "tag_triangle": "drug_sh",
        "name": "بوکمارک تغییر رنگ اسمارت ابجکت اعتیاد",
        "positive_labels": [],
        "negative_labels": []
    },
    "family_problem_so": {
        "tag_circle": "Family_so",
        "tag_triangle": "family_sh",
        "name": "بوکمارک تغییر رنگ اسمارت ابجکت مشکلات خانوادگی",
        "positive_labels": [],
        "negative_labels": []
    },
    "game_addiction_so": {
        "tag_circle": "Mobile_so",
        "tag_triangle": "game_sh",
        "name": "بوکمارک تغییر رنگ اسمارت ابجکت اعتیاد به بازی",
        "positive_labels": [],
        "negative_labels": []
    },
    "interpersonal_so": {
        "tag_circle": "Inter_so",
        "tag_triangle": "inter_sh",
        "name": "بوکمارک تغییر رنگ اسمارت ابجکت مشکلات بین فردی",
        "positive_labels": [],
        "negative_labels": []
    },
    "motivation_so": {
        "tag_circle": "Mot_so",
        "tag_triangle": "mot_sh",
        "name": "بوکمارک تغییر رنگ اسمارت ابجکت بی انگیزگی",
        "positive_labels": [],
        "negative_labels": []
    },
    "ocd_so": {
        "tag_circle": "Ocd_so",
        "tag_triangle": "ocs_sh",
        "name": "بوکمارک تغییر رنگ اسمارت ابجکت وسواس",
        "positive_labels": [],
        "negative_labels": []
    },
    "self_confident_so": {
        "tag_circle": "Con_so",
        "tag_triangle": "conf_sh",
        "name": "بوکمارک تغییر رنگ اسمارت ابجکت اعتماد به نفس",
        "positive_labels": [],
        "negative_labels": []
    },
    "sleep_problem_so": {
        "tag_circle": "Sleep_so",
        "tag_triangle": "sleep_sh",
        "name": "بوکمارک تغییر رنگ اسمارت ابجکت مشکلات خواب",
        "positive_labels": [],
        "negative_labels": []
    },
    "study_problem_so": {
        "tag_circle": "Study_so",
        "tag_triangle": "study_sh",
        "name": "بوکمارک تغییر رنگ اسمارت ابجکت مهارت های مطالعاتی",
        "positive_labels": [],
        "negative_labels": []
    },
    "truma_so": {
        "tag_circle": "Truma_so",
        "tag_triangle": "truma_sh",
        "name": "بوکمارک تغییر رنگ اسمارت ابجکت تروما",
        "positive_labels": [],
        "negative_labels": []
    },
    "wage_future_so": {
        "tag_circle": "Future_so",
        "tag_triangle": "future_sh",
        "name": "بوکمارک تغییر رنگ اسمارت ابجکت اینده مبهم",
        "positive_labels": [],
        "negative_labels": []
    },
    "ideal_so": {
        "tag_circle": "Ideal_so",
        "tag_triangle": "ideal_sh",
        "name": "بوکمارک تغییر رنگ اسمارت ابجکت کمالگرایی",
        "positive_labels": [],
        "negative_labels": []
    }
}

OTHER_TAGS = {
    "vav": {
        "name": "اولویت 1 تغییر عوامل سطحی",
        "positive_labels": [],
        "negative_labels": []
    },
    "vaav": {
        "name": "اولویت 2 تغییر عوامل سطجی",
        "positive_labels": [],
        "negative_labels": []
    },
    "vaaav": {
        "name": "اولویت 3 تغییر عوامل سطحی",
        "positive_labels": [],
        "negative_labels": []
    },
    "vaaaav": {
        "name": "اولویت 4 تغییر عوامل سطجی",
        "positive_labels": [],
        "negative_labels": []
    },
    "vaaaaav": {
        "name": "اولویت 5 تغییر عوامل سطحی",
        "positive_labels": [],
        "negative_labels": []
    },
    "waw": {
        "name": "اولویت 1 تغییر عوامل روانشناختی",
        "positive_labels": [],
        "negative_labels": []
    },
    "waaw": {
        "name": "اولویت 2 تغییر عوامل روانشناختی",
        "positive_labels": [],
        "negative_labels": []
    },
    "waaaw": {
        "name": "اولویت 3 تغییر عوامل روانشناختی",
        "positive_labels": [],
        "negative_labels": []
    },
    "waaaaw": {
        "name": "اولویت 4 تغییر عوامل روانشناختی",
        "positive_labels": [],
        "negative_labels": []
    },
    "waaaaaw": {
        "name": "اولویت 5 تغییر عوامل روانشناختی",
        "positive_labels": [],
        "negative_labels": []
    },
    "zaz": {
        "name": "اولویت 1 تغییر عوامل بنیادین",
        "positive_labels": [],
        "negative_labels": []
    },
    "zaaz": {
        "name": "اولویت 2 تغییر عوامل بنیادین",
        "positive_labels": [],
        "negative_labels": []
    },
    "zaaaz": {
        "name": "اولویت 3 تغییر عوامل بنیادین",
        "positive_labels": [],
        "negative_labels": []
    },
    "zaaaaz": {
        "name": "اولویت 4 تغییر عوامل بنیادین",
        "positive_labels": [],
        "negative_labels": []
    },
    "zaaaaaz": {
        "name": "اولویت 5 تغییر عوامل بنیادین",
        "positive_labels": [],
        "negative_labels": []
    },
    "addictionadvice": {
        "name": "راهکار اعتیاد",
        "positive_labels": [],
        "negative_labels": []
    },
    "bodyadvice": {
        "name": "راهکار مشکلات جسمی",
        "positive_labels": [],
        "negative_labels": []
    },
    "sleepadvice": {
        "name": "راهکار مشکلات خواب",
        "positive_labels": [],
        "negative_labels": []
    },
    "mobileadvice": {
        "name": "راهکار اعتیاد به اینترنت",
        "positive_labels": [],
        "negative_labels": []
    },
    "wagefutureadvice": {
        "name": "راهکار اینده مبهم",
        "positive_labels": [],
        "negative_labels": []
    },
    "studyadvice": {
        "name": "راهکار مهارت های مطالعاتی",
        "positive_labels": [],
        "negative_labels": []
    },
    "anxadvice": {
        "name": "راهکار اضطراب",
        "positive_labels": [],
        "negative_labels": []
    },
    "depadvice": {
        "name": "راهکار افسردگی",
        "positive_labels": [],
        "negative_labels": []
    },
    "ocdadvice": {
        "name": "راهکار وسواس",
        "positive_labels": [],
        "negative_labels": []
    },
    "motadvice": {
        "name": "راهکار بی انگیزگی",
        "positive_labels": [],
        "negative_labels": []
    },
    "confadvice": {
        "name": "راهکار اعتماد به نفس",
        "positive_labels": [],
        "negative_labels": []
    },
    "adhdadvice": {
        "name": "راهکار بیش فعالی",
        "positive_labels": [],
        "negative_labels": []
    },
    "familyadvice": {
        "name": "راهکار مشکلات خانوادگی",
        "positive_labels": [],
        "negative_labels": []
    },
    "interadvice": {
        "name": "راهکار مشکلات بین فردی",
        "positive_labels": [],
        "negative_labels": []
    },
    "trumaadvice": {
        "name": "راهکار تروما",
        "positive_labels": [],
        "negative_labels": []
    },
    "addictstatefast": {
        "name": "وضعیت اعتیاد",
        "positive_labels": [],
        "negative_labels": []
    },
    "addictinterfast": {
        "name": "اولویت مداخله اعتیاد",
        "positive_labels": [],
        "negative_labels": []
    },
    "addictscorefast": {
        "name": "نمره اعتیاد",
        "positive_labels": [],
        "negative_labels": []
    },
    "addictfast": {
        "name": "مداخله اعتیاد کارنامه اجمالی",
        "positive_labels": [],
        "negative_labels": []
    },
    "bodystatefast": {
        "name": "وضعیت مشکلات جسمی",
        "positive_labels": [],
        "negative_labels": []
    },
    "bodyinterfast": {
        "name": "اولویت مداخله مشکلات جسمی",
        "positive_labels": [],
        "negative_labels": []
    },
    "bodyscorefast": {
        "name": "نمره مشکلات جسمی",
        "positive_labels": [],
        "negative_labels": []
    },
    "bodyfast": {
        "name": "مداخله مشکلات جسمی کارنامه اجمالی",
        "positive_labels": [],
        "negative_labels": []
    },
    "sleepstatefast": {
        "name": "وضعیت مشکلات خواب",
        "positive_labels": [],
        "negative_labels": []
    },
    "sleepinterfast": {
        "name": "اولویت مداخله مشکلات خواب",
        "positive_labels": [],
        "negative_labels": []
    },
    "sleepscorefast": {
        "name": "نمره مشکلات خواب",
        "positive_labels": [],
        "negative_labels": []
    },
    "sleepfast": {
        "name": "مداخله مشکلات خواب کارنامه اجمالی",
        "positive_labels": [],
        "negative_labels": []
    },
    "futurestatefast": {
        "name": "وضعیت ابهام اینده",
        "positive_labels": [],
        "negative_labels": []
    },
    "futureinterfast": {
        "name": "اولویت مداخله ابهام اینده",
        "positive_labels": [],
        "negative_labels": []
    },
    "futurescorefast": {
        "name": "نمره ابهام اینده",
        "positive_labels": [],
        "negative_labels": []
    },
    "futurefast": {
        "name": "مداخله ابهام اینده کارنامه اجمالی",
        "positive_labels": [],
        "negative_labels": []
    },
    "gamestatefast": {
        "name": "وضعیت اعتیاد بازی",
        "positive_labels": [],
        "negative_labels": []
    },
    "gameinterfast": {
        "name": "اولویت مداخله اعتیاد بازی",
        "positive_labels": [],
        "negative_labels": []
    },
    "gamescorefast": {
        "name": "نمره اعتیاد بازی",
        "positive_labels": [],
        "negative_labels": []
    },
    "gamefast": {
        "name": "مداخله اعتیاد  بازی کارنامه اجمالی",
        "positive_labels": [],
        "negative_labels": []
    },
    "studystatefast": {
        "name": "وضعیت مشکلات مطالعاتی",
        "positive_labels": [],
        "negative_labels": []
    },
    "studyinterfast": {
        "name": "اولویت مداخله مشکلات مطالعاتی",
        "positive_labels": [],
        "negative_labels": []
    },
    "studyscorefast": {
        "name": "نمره مشکلات مطالعاتی",
        "positive_labels": [],
        "negative_labels": []
    },
    "studyfast": {
        "name": "مداخله مشکلات مطالعاتی کارنامه اجمالی",
        "positive_labels": [],
        "negative_labels": []
    },
    "depstatefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "depinterfast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "depscorefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "depfast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "anxstatefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "anxinterfast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "anxscorefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "anxfast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "ocdstatefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "ocdinterfast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "ocdscorefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "ocdfast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "motivestatefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "motiveinterfast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "motivescorefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "motivefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "confstatefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "confinterfast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "confscorefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "conffast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "ptsdstatefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "ptsdinterfast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "ptsdscorefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "ptsdfast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "adhdstatefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "adhdinterfast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "adhdscorefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "adhdfast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "familystatefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "familyinterfast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "familyscorefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "familyfast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "interpstatefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "interpinterfast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "interpscorefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "interpfast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "idealstatefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "idealinterfast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "idealscorefast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    },
    "idealfast": {
        "name": "",
        "positive_labels": [],
        "negative_labels": []
    }
}


def get_bookmark_info(tag):
    """
    Returns the info object (name, positive and negative labels) for a given tag.
    """
    return CALC_DATA.get(tag)
